server:
  port: 8080

spring:
  application:
    name: user-api
  data:
    mongodb:
      uri: mongodb://root:example@localhost:27017/admin

  jackson:
    serialization:
      write-dates-as-timestamps: false

api:
  project:
    version: @project.version@
  github-user:
    url: https://api.github.com

logging:
  level:
    br.com.user.api: debug

feign:
  client:
    config:
      default:
        connectTimeout: 30000
        readTimeout: 60000

management:
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    export:
      prometheus:
        enabled: true
